package com.example.betano.enums;

public enum TeamNames {
    CFR_CLUJ, FCSB, DINAMO_BUCURESTI,
    VIITORUL_CONSTANTA, CSU_CRAIOVA,
    GAZ_METAN_MEDIAS, ASTRA_GIURGIU, ACADEMICA_CLINCENI,
    FC_VOLUNTARI, POLI_IASI, FC_BOTOSANI,
    FC, HERMANNSTADT, SEPSI, CHINDIA_TARGOVISTE;
}
